### ISSUE TITLE
Missing weights

### ISSUE THREAD

**Issue by arstek131** [alessandro-crescenzi/computer_vision_project#2]
In order to perform inference, could you provide the mentioned weights in the Test section?

Moreover I think you need to specify that the provided commands in Test section are suitable in a Jupyter notebook environment, using _!_ in a command line in Unix-like shells triggers history expansion, and I think it's not the intended behavior.
Thanks

**Comment by alessandro-crescenzi** [comment]
Hi @arstek131 , I'm very happy to know you interested in our project. You're absolutely right! I forgot to say where to pick the weights of the 2 networks. I will do it now. If in the meanwhile you have any doubts, I'm very happy to discuss about
